# Form implementation generated from reading ui file '/home/neosahadeo/Documents/Projects/Python/1337x/ui/list_item.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(1241, 56)
        Frame.setStyleSheet("background-color: #232323;\n"
"color: rgb(255, 255, 255);")
        self.item = QtWidgets.QFrame(parent=Frame)
        self.item.setGeometry(QtCore.QRect(9, 10, 1211, 41))
        self.item.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.item.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.item.setObjectName("item")
        self.widget = QtWidgets.QWidget(parent=self.item)
        self.widget.setGeometry(QtCore.QRect(0, 8, 1211, 31))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkbox = QtWidgets.QCheckBox(parent=self.widget)
        self.checkbox.setStyleSheet("QCheckBox::indicator {\n"
"    width: 25px;\n"
"    height: 25px;\n"
"}\n"
"QCheckBox {\n"
"border: 1px solid white;\n"
"}\n"
"")
        self.checkbox.setText("")
        self.checkbox.setChecked(True)
        self.checkbox.setObjectName("checkbox")
        self.horizontalLayout.addWidget(self.checkbox)
        self.label = QtWidgets.QLabel(parent=self.widget)
        self.label.setEnabled(True)
        self.label.setMinimumSize(QtCore.QSize(0, 21))
        self.label.setStyleSheet("font: 12pt \"Sans Serif\";")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.horizontalLayout.setStretch(1, 3)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.label.setText(_translate("Frame", "Hello world "))
