# Form implementation generated from reading ui file '/home/neosahadeo/Documents/Projects/Python/1337x/ui/loading.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Loading(object):
    def setupUi(self, Loading):
        Loading.setObjectName("Loading")
        Loading.resize(862, 445)
        Loading.setStyleSheet("background-color: black;")
        self.textBrowser = QtWidgets.QTextBrowser(parent=Loading)
        self.textBrowser.setGeometry(QtCore.QRect(15, 61, 831, 361))
        self.textBrowser.setStyleSheet("color: white;\n"
"border: 1px solid white;\n"
"border-radius: 3px;")
        self.textBrowser.setObjectName("textBrowser")
        self.label = QtWidgets.QLabel(parent=Loading)
        self.label.setGeometry(QtCore.QRect(20, 30, 61, 21))
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-size: 17px;")
        self.label.setObjectName("label")

        self.retranslateUi(Loading)
        QtCore.QMetaObject.connectSlotsByName(Loading)

    def retranslateUi(self, Loading):
        _translate = QtCore.QCoreApplication.translate
        Loading.setWindowTitle(_translate("Loading", "Frame"))
        self.textBrowser.setHtml(_translate("Loading", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">DEMO</p></body></html>"))
        self.label.setText(_translate("Loading", "Logs"))
