# Form implementation generated from reading ui file '/home/neosahadeo/Documents/Projects/Python/1337x/ui/main_window.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: #232323;")
        MainWindow.setTabShape(QtWidgets.QTabWidget.TabShape.Rounded)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.queueSelected = QtWidgets.QPushButton(parent=self.centralwidget)
        self.queueSelected.setGeometry(QtCore.QRect(1130, 680, 121, 25))
        self.queueSelected.setAutoFillBackground(False)
        self.queueSelected.setStyleSheet("background-color: rgb(17, 88, 13);\n"
"color: white;")
        self.queueSelected.setObjectName("queueSelected")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(10, 60, 1241, 591))
        self.scrollArea.setStyleSheet("QScrollArea QScrollBar:vertical {\n"
"    background-color: black; /* orange track background */\n"
"    width: 10px;\n"
"    margin: 15px 0 15px 0;\n"
"    border-radius: 7px;\n"
"}\n"
"\n"
"QScrollArea QScrollBar::handle:vertical {\n"
"    background-color: white; /* darker orange handle */\n"
"    min-height: 30px;\n"
"    border-radius: 7px;\n"
"}\n"
"\n"
"QScrollArea QScrollBar::handle:vertical:hover {\n"
"    background-color: white; /* lighter orange on hover */\n"
"}\n"
"\n"
"QScrollArea QScrollBar::handle:vertical:pressed {\n"
"    background-color: #FF7F00; /* pressed state */\n"
"}\n"
"\n"
"QScrollArea QScrollBar::sub-line:vertical,\n"
"QScrollArea QScrollBar::add-line:vertical {\n"
"    background-color: #FFA500; /* scrollbar buttons background */\n"
"    height: 15px;\n"
"    border-radius: 7px;\n"
"    border: none;\n"
"}\n"
"\n"
"QScrollArea QScrollBar::sub-line:vertical:hover,\n"
"QScrollArea QScrollBar::add-line:vertical:hover {\n"
"    background-color: #FF8C00; /* hover state for buttons */\n"
"}\n"
"\n"
"QScrollArea QScrollBar::up-arrow:vertical,\n"
"QScrollArea QScrollBar::down-arrow:vertical {\n"
"    background: none; /* hide arrows or customize if needed */\n"
"}\n"
"\n"
"QScrollArea QScrollBar::add-page:vertical,\n"
"QScrollArea QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1239, 589))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.scrollAreaWidgetContents)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 1221, 571))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.searchNab = QtWidgets.QFrame(parent=self.centralwidget)
        self.searchNab.setGeometry(QtCore.QRect(9, 10, 671, 41))
        self.searchNab.setStyleSheet("")
        self.searchNab.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.searchNab.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.searchNab.setObjectName("searchNab")
        self.searchBox = QtWidgets.QLineEdit(parent=self.searchNab)
        self.searchBox.setGeometry(QtCore.QRect(12, 10, 401, 25))
        self.searchBox.setMaximumSize(QtCore.QSize(401, 16777215))
        self.searchBox.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.searchBox.setText("")
        self.searchBox.setObjectName("searchBox")
        self.splitter = QtWidgets.QSplitter(parent=self.searchNab)
        self.splitter.setGeometry(QtCore.QRect(420, 10, 240, 25))
        self.splitter.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"}\n"
"color: black;")
        self.splitter.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.splitter.setObjectName("splitter")
        self.search = QtWidgets.QPushButton(parent=self.splitter)
        self.search.setStyleSheet("")
        self.search.setObjectName("search")
        self.prevPage = QtWidgets.QPushButton(parent=self.splitter)
        self.prevPage.setStyleSheet("")
        self.prevPage.setObjectName("prevPage")
        self.nextPage = QtWidgets.QPushButton(parent=self.splitter)
        self.nextPage.setStyleSheet("")
        self.nextPage.setObjectName("nextPage")
        self.closeButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.closeButton.setGeometry(QtCore.QRect(1170, 20, 81, 25))
        self.closeButton.setStyleSheet("background-color: rgb(255, 112, 112);")
        icon = QtGui.QIcon.fromTheme(QtGui.QIcon.ThemeIcon.ListRemove)
        self.closeButton.setIcon(icon)
        self.closeButton.setObjectName("closeButton")
        self.layoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 690, 343, 26))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label.setMinimumSize(QtCore.QSize(301, 17))
        self.label.setStyleSheet("font: 600 12pt \"URW Gothic\";\n"
"color: #F14E13;")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.githubButton = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.githubButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/home/neosahadeo/Documents/Projects/Python/1337x/ui/resources/github-142-svgrepo-com.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.githubButton.setIcon(icon)
        self.githubButton.setObjectName("githubButton")
        self.horizontalLayout.addWidget(self.githubButton)
        self.selectAllButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.selectAllButton.setGeometry(QtCore.QRect(10, 660, 81, 25))
        self.selectAllButton.setStyleSheet("background-color: white")
        self.selectAllButton.setObjectName("selectAllButton")
        self.categoryButton = QtWidgets.QComboBox(parent=self.centralwidget)
        self.categoryButton.setGeometry(QtCore.QRect(690, 20, 121, 25))
        self.categoryButton.setStyleSheet("QComboBox {\n"
"background-color: white;\n"
"color: black;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background-color: white;\n"
"    color: black; /* normal text color */\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item {\n"
"    background-color: white;\n"
"    color: black;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item:hover {\n"
"    background-color: #F14E13;\n"
"    color: black; /* hovered text color */\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item:selected {\n"
"    background-color: #F14E13FF;\n"
"    color: black;\n"
"}\n"
"")
        self.categoryButton.setObjectName("categoryButton")
        self.categoryButton.addItem("")
        self.categoryButton.addItem("")
        self.categoryButton.addItem("")
        self.categoryButton.addItem("")
        self.categoryButton.addItem("")
        self.categoryButton.addItem("")
        self.categoryButton.addItem("")
        self.categoryButton.addItem("")
        self.categoryButton.addItem("")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.queueSelected.setToolTip(_translate("MainWindow", "<html><head/><body><p>Queue all selected torrents into your torrent manager</p></body></html>"))
        self.queueSelected.setText(_translate("MainWindow", "Queue Selected"))
        self.search.setText(_translate("MainWindow", "Search"))
        self.prevPage.setText(_translate("MainWindow", "Prev Page"))
        self.nextPage.setText(_translate("MainWindow", "Next Page"))
        self.closeButton.setText(_translate("MainWindow", "Close"))
        self.label.setText(_translate("MainWindow", "1337x (Unofficial) Torrent Frontend Beta"))
        self.selectAllButton.setText(_translate("MainWindow", "Selected All"))
        self.categoryButton.setItemText(0, _translate("MainWindow", "TV"))
        self.categoryButton.setItemText(1, _translate("MainWindow", "Movies"))
        self.categoryButton.setItemText(2, _translate("MainWindow", "Games"))
        self.categoryButton.setItemText(3, _translate("MainWindow", "Music"))
        self.categoryButton.setItemText(4, _translate("MainWindow", "Apps"))
        self.categoryButton.setItemText(5, _translate("MainWindow", "Documentaries"))
        self.categoryButton.setItemText(6, _translate("MainWindow", "Anime"))
        self.categoryButton.setItemText(7, _translate("MainWindow", "Other"))
        self.categoryButton.setItemText(8, _translate("MainWindow", "XXX"))
